# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38d9caef279ce3bfdf121175582048f1b6d74918da7cc7170a28ec24c899c4dbf0877c28cc33abf30ea3c1dfb469eec4627eab3a8c4ce7848f67a94c70a87dfb

test:
  secret_key_base: c8502561f046f68cb10ca0f4f5182821b507c6c85f82b30b3485d0020ffbc31302abf00e2a47977d67745a3dde9d5ecd67d7799f964f215688bd9e83c82a3e89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
